draft formation Docker: vos questions
saegus/formations pull request #1
Opened 2023-01-17 14:32 UTC by AnisSjd

2023-01-18 11:54 UTC, eBauman-factory commented on script-intro-docker.md
> +    You need to specify one of the following as an environment variable:
donc c'est l'image mysql qui a besoin de ces variables d'environnements, elles sont obligatoire pour le bon fonctionnement de l'image ?

2023-02-24 13:04 UTC, drillskibo requested changes
😃

2023-02-24 15:01 UTC, AnisSjd commented on script-intro-docker.md
> +
Note: À la fin de la formation docker V2 (images, volumes et réseau), au moment de parler de la formation V3, j'ai dit que tout ce qu'on a vu sert à préparer le chapitre sur les DCF. Diesen avait peur que tout ce qu'on a vu jusque-là n'ait été que peu utile. Il faut préciser que peut-être que les commandes qu'on a vu ne lui serviront que peu, mais les concepts qu'elles implémentent et leurs interactions sont nécessaires à la compréhension des DCFs

Également, on n'a pas vu les volumes cached/delegated ni les types de réseaux (bridge, ...) ni le fonctionnement des réseaux (externalisé dans un article) ni le fait que la communication entre containers au sein d'un même réseau se fait en utilisant le nom du conteneur comme hostname.

Il faut de plus corriger les exemples qui ne sont pas cohérents, ou qui ont besoin d'un archi existante ("mkdir  mon-front; touch mon-front/package.json", etc )

2023-03-15 12:07 UTC, diesen-hub commented
example 1 clean :
Le code permet d'afficher le nombre de joueur si l'utilisateur est un admin

2023-03-15 12:08 UTC, GillesFONO-saegus commented
Ex1 Original : recupère ... dans  ClassementAPI
class s'appelle Classement extends de composant
constructeur initialise       listUser: [], currentView: "point",viewMonde: false,
a la méthode d'entrée this._loadDataClassement();
qui  remplit tabBatch => state en fonction du user
définition :   _setCurrentView = (view) => {} // https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1

  _calculMauvaiseReponse = (item) => {};

  _renderPoint(item) {}

  _renderPodiumElement(user) {}

  render: affichage qui affiche le nombre de joueur  par indicateur si user admin

2023-03-15 12:15 UTC, diesen-hub commented
question bonus 1:
si non admin Nb joueurs: null (joueurs)

2023-03-15 12:16 UTC, Neskwik93 commented on clean-code/exemple_1_clean.js
> +const ClassementAPI = require("...");
composant classement qui a pour state une liste d'utilisateur, une current view et un viewMonde qui doit être viewMonde
à l'init on check si l'utilisateur est admin
dans les deux cas on récupère le classement mais si on est admin on récupère les indicateurs aussi
le rendu final affiche juste le nombre de joueur si on est admin si non ça affiche classements du programme en cours et c'est tout
ça n'a pas d'interet si on est pas admin 
on a des fonctions qui ne sont pas appelées et pas utilisées 
  _setCurrentView = (view) => {}

  _calculMauvaiseReponse = (item) => {};

  _renderPoint(item) {}

  _renderPodiumElement(user) {}

question bonus on aurait pas eu les indicateurs donc ça aurait été différents de -1 donc on aurait eu 
Nb joueurs: undefinedjoueurs

2023-03-15 12:30 UTC, StoneSaegus commented
Le composant a comme variable une liste d'utilisateur, currentview et veiwmonde, une fois le composant monté on lance la fonction loaddataclassement

Si l'utilisateur est un administrateur la vue rend un classement sinon l'utilisateur ne voit que le h1 bien qu'il y ait un appel qui soit fait à la fonction getClassement

2023-03-15 12:38 UTC, diesen-hub commented
original example 2

Le code permet si le user n'est pas admin de récupérer son nombre de trophés 

Question Bonus

Le champ before renvoie tous les trophées de n - 2 jours
Ce nom parce que se sont des trophées précédement gagnée

2023-03-15 12:42 UTC, GillesFONO-saegus commented
Exo 2 clean
Recupere hapiHandler, HTTPResponse, dailyRewards

route get path : baseUrl + "/current-reward" avec méthode hapiHandler(getCurrentRewardController),

init method getCurrentRewardController qui retour un payload true is admin ou bien un 
rewardsDetails(UserLogins, user) qui est une method qui pour un user renvoi 
     current: dailyRewards[nbDaysOfConnexion],
    before: return dailyRewards.slice(rewardStartIndex, nbDaysOfConnexion);,
    after: dailyRewards en fonction du nombre de co

before renvoie previousRewards(dailyRewards, nbDaysOfConnexion)

2023-09-26 12:05 UTC, merged